---
title: "About"
---

## Instructor

I am a **Postdoctoral Researcher at Kansas State University**. My work combines agricultural field research, soil fertility, nutrient management, statistics, and data science.

### Education

- **PhD in Agronomy**, Kansas State University
- **MS in Statistics**, Kansas State University
- **MS in Agronomy,**, Kansas State University
- **MS in Food Security**, UnADM
- **BS in Agronomic Engineering**, EARTH University

[Personal website](https://gustavo-roa.github.io/)

## Workshop Data

The workshop uses a subset of data from the following study:

**Roa, G. A.**, & Ruiz Diaz, D. A. (2026). Assessing corn response to sulfur fertilization in Kansas: Efficiency, optimum rate, and diagnostic tools. Agronomy Journal, 118, e70337. https://doi.org/10.1002/agj2.70337

The study evaluated corn response to sulfur fertilization across Kansas and included measurements of grain yield, tissue sulfur concentration, sulfur uptake, and sulfur rate-response.

[Read the paper](https://acsess.onlinelibrary.wiley.com/doi/10.1002/agj2.70337)